# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trolley.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_trolleyWindow(object):
    def setupUi(self, trolleyWindow):
        trolleyWindow.setObjectName(_fromUtf8("trolleyWindow"))
        trolleyWindow.resize(854, 673)
        self.centralwidget = QtGui.QWidget(trolleyWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 20, 670, 520))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(255, 255, 255);"))
        self.stackedWidget.setFrameShape(QtGui.QFrame.Box)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pageConsent = QtGui.QWidget()
        self.pageConsent.setObjectName(_fromUtf8("pageConsent"))
        self.consentContinueButton = QtGui.QPushButton(self.pageConsent)
        self.consentContinueButton.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.consentContinueButton.setFont(font)
        self.consentContinueButton.setAutoFillBackground(False)
        self.consentContinueButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.consentContinueButton.setObjectName(_fromUtf8("consentContinueButton"))
        self.label_15 = QtGui.QLabel(self.pageConsent)
        self.label_15.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.consentInfo = QtGui.QLabel(self.pageConsent)
        self.consentInfo.setGeometry(QtCore.QRect(50, 90, 581, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.consentInfo.setFont(font)
        self.consentInfo.setWordWrap(True)
        self.consentInfo.setObjectName(_fromUtf8("consentInfo"))
        self.consentInfo_2 = QtGui.QLabel(self.pageConsent)
        self.consentInfo_2.setGeometry(QtCore.QRect(50, 60, 581, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.consentInfo_2.setFont(font)
        self.consentInfo_2.setWordWrap(True)
        self.consentInfo_2.setObjectName(_fromUtf8("consentInfo_2"))
        self.consentInfo_4 = QtGui.QLabel(self.pageConsent)
        self.consentInfo_4.setGeometry(QtCore.QRect(50, 240, 581, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.consentInfo_4.setFont(font)
        self.consentInfo_4.setWordWrap(True)
        self.consentInfo_4.setObjectName(_fromUtf8("consentInfo_4"))
        self.consentInfo_3 = QtGui.QLabel(self.pageConsent)
        self.consentInfo_3.setGeometry(QtCore.QRect(50, 170, 581, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.consentInfo_3.setFont(font)
        self.consentInfo_3.setWordWrap(True)
        self.consentInfo_3.setObjectName(_fromUtf8("consentInfo_3"))
        self.consentBox = QtGui.QCheckBox(self.pageConsent)
        self.consentBox.setEnabled(True)
        self.consentBox.setGeometry(QtCore.QRect(200, 430, 371, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.consentBox.setFont(font)
        self.consentBox.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.consentBox.setCheckable(True)
        self.consentBox.setTristate(False)
        self.consentBox.setObjectName(_fromUtf8("consentBox"))
        self.stackedWidget.addWidget(self.pageConsent)
        self.pageDemog = QtGui.QWidget()
        self.pageDemog.setObjectName(_fromUtf8("pageDemog"))
        self.demogContinueButton = QtGui.QPushButton(self.pageDemog)
        self.demogContinueButton.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.demogContinueButton.setFont(font)
        self.demogContinueButton.setAutoFillBackground(False)
        self.demogContinueButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.demogContinueButton.setObjectName(_fromUtf8("demogContinueButton"))
        self.labelErrorGender = QtGui.QLabel(self.pageDemog)
        self.labelErrorGender.setGeometry(QtCore.QRect(440, 220, 111, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelErrorGender.setFont(font)
        self.labelErrorGender.setStyleSheet(_fromUtf8("color: rgb(252, 7, 22);"))
        self.labelErrorGender.setWordWrap(True)
        self.labelErrorGender.setObjectName(_fromUtf8("labelErrorGender"))
        self.labelErrorAge = QtGui.QLabel(self.pageDemog)
        self.labelErrorAge.setGeometry(QtCore.QRect(440, 140, 111, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelErrorAge.setFont(font)
        self.labelErrorAge.setStyleSheet(_fromUtf8("color: rgb(252, 7, 22);"))
        self.labelErrorAge.setWordWrap(True)
        self.labelErrorAge.setObjectName(_fromUtf8("labelErrorAge"))
        self.labelErrorEducation = QtGui.QLabel(self.pageDemog)
        self.labelErrorEducation.setGeometry(QtCore.QRect(440, 310, 111, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelErrorEducation.setFont(font)
        self.labelErrorEducation.setStyleSheet(_fromUtf8("color: rgb(252, 7, 22);"))
        self.labelErrorEducation.setWordWrap(True)
        self.labelErrorEducation.setObjectName(_fromUtf8("labelErrorEducation"))
        self.UserEducation = QtGui.QWidget(self.pageDemog)
        self.UserEducation.setGeometry(QtCore.QRect(100, 300, 321, 61))
        self.UserEducation.setObjectName(_fromUtf8("UserEducation"))
        self.Education = QtGui.QComboBox(self.UserEducation)
        self.Education.setGeometry(QtCore.QRect(140, 20, 181, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.Education.setFont(font)
        self.Education.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Education.setObjectName(_fromUtf8("Education"))
        self.Education.addItem(_fromUtf8(""))
        self.Education.setItemText(0, _fromUtf8(""))
        self.Education.addItem(_fromUtf8(""))
        self.Education.addItem(_fromUtf8(""))
        self.Education.addItem(_fromUtf8(""))
        self.Education.addItem(_fromUtf8(""))
        self.Education.addItem(_fromUtf8(""))
        self.labelEducation = QtGui.QLabel(self.UserEducation)
        self.labelEducation.setGeometry(QtCore.QRect(10, 20, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelEducation.setFont(font)
        self.labelEducation.setObjectName(_fromUtf8("labelEducation"))
        self.labelDemog = QtGui.QLabel(self.pageDemog)
        self.labelDemog.setGeometry(QtCore.QRect(110, 60, 461, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDemog.setFont(font)
        self.labelDemog.setObjectName(_fromUtf8("labelDemog"))
        self.UserGender = QtGui.QWidget(self.pageDemog)
        self.UserGender.setGeometry(QtCore.QRect(100, 210, 321, 80))
        self.UserGender.setObjectName(_fromUtf8("UserGender"))
        self.Male = QtGui.QRadioButton(self.UserGender)
        self.Male.setGeometry(QtCore.QRect(140, 10, 82, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Male.setFont(font)
        self.Male.setObjectName(_fromUtf8("Male"))
        self.Female = QtGui.QRadioButton(self.UserGender)
        self.Female.setGeometry(QtCore.QRect(140, 40, 82, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Female.setFont(font)
        self.Female.setObjectName(_fromUtf8("Female"))
        self.labelGender = QtGui.QLabel(self.UserGender)
        self.labelGender.setGeometry(QtCore.QRect(10, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelGender.setFont(font)
        self.labelGender.setObjectName(_fromUtf8("labelGender"))
        self.UserAge = QtGui.QWidget(self.pageDemog)
        self.UserAge.setGeometry(QtCore.QRect(100, 140, 321, 61))
        self.UserAge.setObjectName(_fromUtf8("UserAge"))
        self.Age = QtGui.QSpinBox(self.UserAge)
        self.Age.setGeometry(QtCore.QRect(140, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Age.setFont(font)
        self.Age.setObjectName(_fromUtf8("Age"))
        self.labelAge = QtGui.QLabel(self.UserAge)
        self.labelAge.setGeometry(QtCore.QRect(10, 20, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelAge.setFont(font)
        self.labelAge.setObjectName(_fromUtf8("labelAge"))
        self.label_19 = QtGui.QLabel(self.pageDemog)
        self.label_19.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.stackedWidget.addWidget(self.pageDemog)
        self.pageBrochure = QtGui.QWidget()
        self.pageBrochure.setObjectName(_fromUtf8("pageBrochure"))
        self.brochureContinueButton = QtGui.QPushButton(self.pageBrochure)
        self.brochureContinueButton.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.brochureContinueButton.setFont(font)
        self.brochureContinueButton.setAutoFillBackground(False)
        self.brochureContinueButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.brochureContinueButton.setObjectName(_fromUtf8("brochureContinueButton"))
        self.label_12 = QtGui.QLabel(self.pageBrochure)
        self.label_12.setGeometry(QtCore.QRect(290, 30, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.widget = QtGui.QWidget(self.pageBrochure)
        self.widget.setGeometry(QtCore.QRect(130, 180, 401, 251))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.person2_12 = QtGui.QLabel(self.widget)
        self.person2_12.setGeometry(QtCore.QRect(330, 190, 50, 50))
        self.person2_12.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_12.setText(_fromUtf8(""))
        self.person2_12.setPixmap(QtGui.QPixmap(_fromUtf8("Boy3.jpg")))
        self.person2_12.setScaledContents(True)
        self.person2_12.setObjectName(_fromUtf8("person2_12"))
        self.person3_9 = QtGui.QLabel(self.widget)
        self.person3_9.setGeometry(QtCore.QRect(180, 70, 50, 50))
        self.person3_9.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3_9.setText(_fromUtf8(""))
        self.person3_9.setPixmap(QtGui.QPixmap(_fromUtf8("Girl2.jpg")))
        self.person3_9.setScaledContents(True)
        self.person3_9.setObjectName(_fromUtf8("person3_9"))
        self.personSidetrack_2 = QtGui.QLabel(self.widget)
        self.personSidetrack_2.setGeometry(QtCore.QRect(30, 10, 50, 50))
        self.personSidetrack_2.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.personSidetrack_2.setText(_fromUtf8(""))
        self.personSidetrack_2.setPixmap(QtGui.QPixmap(_fromUtf8("Girl1.jpg")))
        self.personSidetrack_2.setScaledContents(True)
        self.personSidetrack_2.setObjectName(_fromUtf8("personSidetrack_2"))
        self.person1_11 = QtGui.QLabel(self.widget)
        self.person1_11.setGeometry(QtCore.QRect(180, 10, 50, 50))
        self.person1_11.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1_11.setText(_fromUtf8(""))
        self.person1_11.setPixmap(QtGui.QPixmap(_fromUtf8("Boy1.jpg")))
        self.person1_11.setScaledContents(True)
        self.person1_11.setObjectName(_fromUtf8("person1_11"))
        self.person4_9 = QtGui.QLabel(self.widget)
        self.person4_9.setGeometry(QtCore.QRect(180, 130, 50, 50))
        self.person4_9.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4_9.setText(_fromUtf8(""))
        self.person4_9.setPixmap(QtGui.QPixmap(_fromUtf8("Boy4.jpg")))
        self.person4_9.setScaledContents(True)
        self.person4_9.setObjectName(_fromUtf8("person4_9"))
        self.person4_10 = QtGui.QLabel(self.widget)
        self.person4_10.setGeometry(QtCore.QRect(330, 10, 50, 50))
        self.person4_10.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4_10.setText(_fromUtf8(""))
        self.person4_10.setPixmap(QtGui.QPixmap(_fromUtf8("Girl5.jpg")))
        self.person4_10.setScaledContents(True)
        self.person4_10.setObjectName(_fromUtf8("person4_10"))
        self.person2_8 = QtGui.QLabel(self.widget)
        self.person2_8.setGeometry(QtCore.QRect(330, 70, 50, 50))
        self.person2_8.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_8.setText(_fromUtf8(""))
        self.person2_8.setPixmap(QtGui.QPixmap(_fromUtf8("Boy6.jpg")))
        self.person2_8.setScaledContents(True)
        self.person2_8.setObjectName(_fromUtf8("person2_8"))
        self.person5_8 = QtGui.QLabel(self.widget)
        self.person5_8.setGeometry(QtCore.QRect(330, 130, 50, 50))
        self.person5_8.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person5_8.setText(_fromUtf8(""))
        self.person5_8.setPixmap(QtGui.QPixmap(_fromUtf8("Girl6.jpg")))
        self.person5_8.setScaledContents(True)
        self.person5_8.setObjectName(_fromUtf8("person5_8"))
        self.person3_10 = QtGui.QLabel(self.widget)
        self.person3_10.setGeometry(QtCore.QRect(30, 190, 50, 50))
        self.person3_10.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3_10.setText(_fromUtf8(""))
        self.person3_10.setPixmap(QtGui.QPixmap(_fromUtf8("Boy5.jpg")))
        self.person3_10.setScaledContents(True)
        self.person3_10.setObjectName(_fromUtf8("person3_10"))
        self.personFootbridgeSacrifice2_2 = QtGui.QLabel(self.widget)
        self.personFootbridgeSacrifice2_2.setGeometry(QtCore.QRect(30, 70, 50, 50))
        self.personFootbridgeSacrifice2_2.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.personFootbridgeSacrifice2_2.setText(_fromUtf8(""))
        self.personFootbridgeSacrifice2_2.setPixmap(QtGui.QPixmap(_fromUtf8("Boy2.png")))
        self.personFootbridgeSacrifice2_2.setScaledContents(True)
        self.personFootbridgeSacrifice2_2.setObjectName(_fromUtf8("personFootbridgeSacrifice2_2"))
        self.person1_10 = QtGui.QLabel(self.widget)
        self.person1_10.setGeometry(QtCore.QRect(30, 130, 50, 50))
        self.person1_10.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1_10.setText(_fromUtf8(""))
        self.person1_10.setPixmap(QtGui.QPixmap(_fromUtf8("Girl4.jpg")))
        self.person1_10.setScaledContents(True)
        self.person1_10.setObjectName(_fromUtf8("person1_10"))
        self.person2_11 = QtGui.QLabel(self.widget)
        self.person2_11.setGeometry(QtCore.QRect(180, 190, 50, 50))
        self.person2_11.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_11.setText(_fromUtf8(""))
        self.person2_11.setPixmap(QtGui.QPixmap(_fromUtf8("Girl3.jpg")))
        self.person2_11.setScaledContents(True)
        self.person2_11.setObjectName(_fromUtf8("person2_11"))
        self.instructions_4 = QtGui.QLabel(self.pageBrochure)
        self.instructions_4.setGeometry(QtCore.QRect(70, 70, 561, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.instructions_4.setFont(font)
        self.instructions_4.setWordWrap(True)
        self.instructions_4.setObjectName(_fromUtf8("instructions_4"))
        self.label_21 = QtGui.QLabel(self.pageBrochure)
        self.label_21.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.stackedWidget.addWidget(self.pageBrochure)
        self.pageInstructions = QtGui.QWidget()
        self.pageInstructions.setObjectName(_fromUtf8("pageInstructions"))
        self.instructContinueButton = QtGui.QPushButton(self.pageInstructions)
        self.instructContinueButton.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.instructContinueButton.setFont(font)
        self.instructContinueButton.setAutoFillBackground(False)
        self.instructContinueButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.instructContinueButton.setObjectName(_fromUtf8("instructContinueButton"))
        self.instructions = QtGui.QLabel(self.pageInstructions)
        self.instructions.setGeometry(QtCore.QRect(60, 80, 561, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.instructions.setFont(font)
        self.instructions.setWordWrap(True)
        self.instructions.setObjectName(_fromUtf8("instructions"))
        self.instructionsExp1 = QtGui.QLabel(self.pageInstructions)
        self.instructionsExp1.setGeometry(QtCore.QRect(60, 210, 561, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.instructionsExp1.setFont(font)
        self.instructionsExp1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.instructionsExp1.setWordWrap(True)
        self.instructionsExp1.setObjectName(_fromUtf8("instructionsExp1"))
        self.instructionsExp2 = QtGui.QLabel(self.pageInstructions)
        self.instructionsExp2.setGeometry(QtCore.QRect(60, 340, 571, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.instructionsExp2.setFont(font)
        self.instructionsExp2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.instructionsExp2.setWordWrap(True)
        self.instructionsExp2.setObjectName(_fromUtf8("instructionsExp2"))
        self.labelExp1 = QtGui.QLabel(self.pageInstructions)
        self.labelExp1.setGeometry(QtCore.QRect(310, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelExp1.setFont(font)
        self.labelExp1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelExp1.setObjectName(_fromUtf8("labelExp1"))
        self.label_14 = QtGui.QLabel(self.pageInstructions)
        self.label_14.setGeometry(QtCore.QRect(60, 170, 181, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.labelExp2 = QtGui.QLabel(self.pageInstructions)
        self.labelExp2.setGeometry(QtCore.QRect(60, 300, 181, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelExp2.setFont(font)
        self.labelExp2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelExp2.setObjectName(_fromUtf8("labelExp2"))
        self.label_22 = QtGui.QLabel(self.pageInstructions)
        self.label_22.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_22.setText(_fromUtf8(""))
        self.label_22.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.stackedWidget.addWidget(self.pageInstructions)
        self.pageSidetrackDemo1 = QtGui.QWidget()
        self.pageSidetrackDemo1.setObjectName(_fromUtf8("pageSidetrackDemo1"))
        self.frame = QtGui.QFrame(self.pageSidetrackDemo1)
        self.frame.setGeometry(QtCore.QRect(30, 70, 611, 391))
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(239, 239, 239);"))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.ballSidetrackDemo1 = QtGui.QLabel(self.frame)
        self.ballSidetrackDemo1.setGeometry(QtCore.QRect(540, 130, 41, 41))
        self.ballSidetrackDemo1.setText(_fromUtf8(""))
        self.ballSidetrackDemo1.setPixmap(QtGui.QPixmap(_fromUtf8("ball.png")))
        self.ballSidetrackDemo1.setScaledContents(True)
        self.ballSidetrackDemo1.setObjectName(_fromUtf8("ballSidetrackDemo1"))
        self.lineSidetrackDemo1 = QtGui.QFrame(self.frame)
        self.lineSidetrackDemo1.setGeometry(QtCore.QRect(320, 10, 2, 311))
        self.lineSidetrackDemo1.setLineWidth(1)
        self.lineSidetrackDemo1.setMidLineWidth(0)
        self.lineSidetrackDemo1.setFrameShape(QtGui.QFrame.VLine)
        self.lineSidetrackDemo1.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineSidetrackDemo1.setObjectName(_fromUtf8("lineSidetrackDemo1"))
        self.switchDemo1 = QtGui.QLabel(self.frame)
        self.switchDemo1.setGeometry(QtCore.QRect(260, 140, 91, 71))
        self.switchDemo1.setText(_fromUtf8(""))
        self.switchDemo1.setPixmap(QtGui.QPixmap(_fromUtf8("switch1.png")))
        self.switchDemo1.setScaledContents(True)
        self.switchDemo1.setObjectName(_fromUtf8("switchDemo1"))
        self.groupDefaultDemo1 = QtGui.QFrame(self.frame)
        self.groupDefaultDemo1.setGeometry(QtCore.QRect(40, 30, 161, 131))
        self.groupDefaultDemo1.setFrameShape(QtGui.QFrame.NoFrame)
        self.groupDefaultDemo1.setFrameShadow(QtGui.QFrame.Plain)
        self.groupDefaultDemo1.setLineWidth(0)
        self.groupDefaultDemo1.setObjectName(_fromUtf8("groupDefaultDemo1"))
        self.person5 = QtGui.QLabel(self.groupDefaultDemo1)
        self.person5.setGeometry(QtCore.QRect(10, 90, 56, 31))
        self.person5.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person5.setObjectName(_fromUtf8("person5"))
        self.person1 = QtGui.QLabel(self.groupDefaultDemo1)
        self.person1.setGeometry(QtCore.QRect(10, 10, 56, 31))
        self.person1.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1.setObjectName(_fromUtf8("person1"))
        self.person2 = QtGui.QLabel(self.groupDefaultDemo1)
        self.person2.setGeometry(QtCore.QRect(90, 90, 56, 31))
        self.person2.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2.setObjectName(_fromUtf8("person2"))
        self.person4 = QtGui.QLabel(self.groupDefaultDemo1)
        self.person4.setGeometry(QtCore.QRect(90, 10, 56, 31))
        self.person4.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4.setObjectName(_fromUtf8("person4"))
        self.person3 = QtGui.QLabel(self.groupDefaultDemo1)
        self.person3.setGeometry(QtCore.QRect(50, 50, 56, 31))
        self.person3.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3.setObjectName(_fromUtf8("person3"))
        self.groupSacrificeDemo1 = QtGui.QFrame(self.frame)
        self.groupSacrificeDemo1.setGeometry(QtCore.QRect(40, 180, 150, 131))
        self.groupSacrificeDemo1.setFrameShape(QtGui.QFrame.NoFrame)
        self.groupSacrificeDemo1.setFrameShadow(QtGui.QFrame.Plain)
        self.groupSacrificeDemo1.setLineWidth(0)
        self.groupSacrificeDemo1.setObjectName(_fromUtf8("groupSacrificeDemo1"))
        self.person5_3 = QtGui.QLabel(self.groupSacrificeDemo1)
        self.person5_3.setGeometry(QtCore.QRect(10, 90, 56, 31))
        self.person5_3.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person5_3.setObjectName(_fromUtf8("person5_3"))
        self.person1_3 = QtGui.QLabel(self.groupSacrificeDemo1)
        self.person1_3.setGeometry(QtCore.QRect(10, 10, 56, 31))
        self.person1_3.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1_3.setObjectName(_fromUtf8("person1_3"))
        self.person2_3 = QtGui.QLabel(self.groupSacrificeDemo1)
        self.person2_3.setGeometry(QtCore.QRect(90, 90, 56, 31))
        self.person2_3.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_3.setObjectName(_fromUtf8("person2_3"))
        self.person4_3 = QtGui.QLabel(self.groupSacrificeDemo1)
        self.person4_3.setGeometry(QtCore.QRect(90, 10, 56, 31))
        self.person4_3.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4_3.setObjectName(_fromUtf8("person4_3"))
        self.person3_3 = QtGui.QLabel(self.groupSacrificeDemo1)
        self.person3_3.setGeometry(QtCore.QRect(50, 50, 56, 31))
        self.person3_3.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3_3.setObjectName(_fromUtf8("person3_3"))
        self.infoLabelSidetrackDemo1 = QtGui.QLabel(self.frame)
        self.infoLabelSidetrackDemo1.setGeometry(QtCore.QRect(360, 230, 211, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.infoLabelSidetrackDemo1.setFont(font)
        self.infoLabelSidetrackDemo1.setAutoFillBackground(False)
        self.infoLabelSidetrackDemo1.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.infoLabelSidetrackDemo1.setFrameShape(QtGui.QFrame.Box)
        self.infoLabelSidetrackDemo1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.infoLabelSidetrackDemo1.setWordWrap(True)
        self.infoLabelSidetrackDemo1.setObjectName(_fromUtf8("infoLabelSidetrackDemo1"))
        self.frame_9 = QtGui.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(250, 340, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_9.setFont(font)
        self.frame_9.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(255, 255, 255);"))
        self.frame_9.setFrameShape(QtGui.QFrame.Panel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setLineWidth(2)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.label = QtGui.QLabel(self.frame_9)
        self.label.setGeometry(QtCore.QRect(30, 10, 56, 13))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.infoLabelSidetrackDemo1.raise_()
        self.frame_9.raise_()
        self.groupDefaultDemo1.raise_()
        self.groupSacrificeDemo1.raise_()
        self.switchDemo1.raise_()
        self.lineSidetrackDemo1.raise_()
        self.ballSidetrackDemo1.raise_()
        self.continueSidetrackDemo1Button = QtGui.QPushButton(self.pageSidetrackDemo1)
        self.continueSidetrackDemo1Button.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.continueSidetrackDemo1Button.setFont(font)
        self.continueSidetrackDemo1Button.setAutoFillBackground(False)
        self.continueSidetrackDemo1Button.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.continueSidetrackDemo1Button.setObjectName(_fromUtf8("continueSidetrackDemo1Button"))
        self.label_10 = QtGui.QLabel(self.pageSidetrackDemo1)
        self.label_10.setGeometry(QtCore.QRect(310, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_23 = QtGui.QLabel(self.pageSidetrackDemo1)
        self.label_23.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.stackedWidget.addWidget(self.pageSidetrackDemo1)
        self.pageSidetrackDemo2 = QtGui.QWidget()
        self.pageSidetrackDemo2.setObjectName(_fromUtf8("pageSidetrackDemo2"))
        self.continueSidetrackDemo2Button = QtGui.QPushButton(self.pageSidetrackDemo2)
        self.continueSidetrackDemo2Button.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.continueSidetrackDemo2Button.setFont(font)
        self.continueSidetrackDemo2Button.setAutoFillBackground(False)
        self.continueSidetrackDemo2Button.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.continueSidetrackDemo2Button.setObjectName(_fromUtf8("continueSidetrackDemo2Button"))
        self.frame_6 = QtGui.QFrame(self.pageSidetrackDemo2)
        self.frame_6.setGeometry(QtCore.QRect(30, 70, 611, 391))
        self.frame_6.setStyleSheet(_fromUtf8("background-color: rgb(239, 239, 239);"))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.ballSidetrackDemo2 = QtGui.QLabel(self.frame_6)
        self.ballSidetrackDemo2.setGeometry(QtCore.QRect(540, 130, 41, 41))
        self.ballSidetrackDemo2.setText(_fromUtf8(""))
        self.ballSidetrackDemo2.setPixmap(QtGui.QPixmap(_fromUtf8("ball.png")))
        self.ballSidetrackDemo2.setScaledContents(True)
        self.ballSidetrackDemo2.setObjectName(_fromUtf8("ballSidetrackDemo2"))
        self.lineSidetrackDemo2 = QtGui.QFrame(self.frame_6)
        self.lineSidetrackDemo2.setGeometry(QtCore.QRect(320, 10, 2, 311))
        self.lineSidetrackDemo2.setLineWidth(1)
        self.lineSidetrackDemo2.setMidLineWidth(0)
        self.lineSidetrackDemo2.setFrameShape(QtGui.QFrame.VLine)
        self.lineSidetrackDemo2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineSidetrackDemo2.setObjectName(_fromUtf8("lineSidetrackDemo2"))
        self.switchDefaultDemo2 = QtGui.QLabel(self.frame_6)
        self.switchDefaultDemo2.setGeometry(QtCore.QRect(260, 140, 91, 71))
        self.switchDefaultDemo2.setText(_fromUtf8(""))
        self.switchDefaultDemo2.setPixmap(QtGui.QPixmap(_fromUtf8("switch1.png")))
        self.switchDefaultDemo2.setScaledContents(True)
        self.switchDefaultDemo2.setObjectName(_fromUtf8("switchDefaultDemo2"))
        self.switchSidetrackDemo2 = QtGui.QLabel(self.frame_6)
        self.switchSidetrackDemo2.setGeometry(QtCore.QRect(260, 140, 91, 71))
        self.switchSidetrackDemo2.setFrameShadow(QtGui.QFrame.Plain)
        self.switchSidetrackDemo2.setMidLineWidth(0)
        self.switchSidetrackDemo2.setText(_fromUtf8(""))
        self.switchSidetrackDemo2.setPixmap(QtGui.QPixmap(_fromUtf8("switch2.png")))
        self.switchSidetrackDemo2.setScaledContents(True)
        self.switchSidetrackDemo2.setObjectName(_fromUtf8("switchSidetrackDemo2"))
        self.groupDefaultDemo2 = QtGui.QFrame(self.frame_6)
        self.groupDefaultDemo2.setGeometry(QtCore.QRect(40, 30, 161, 131))
        self.groupDefaultDemo2.setFrameShape(QtGui.QFrame.NoFrame)
        self.groupDefaultDemo2.setFrameShadow(QtGui.QFrame.Plain)
        self.groupDefaultDemo2.setLineWidth(0)
        self.groupDefaultDemo2.setObjectName(_fromUtf8("groupDefaultDemo2"))
        self.person5_4 = QtGui.QLabel(self.groupDefaultDemo2)
        self.person5_4.setGeometry(QtCore.QRect(10, 90, 56, 31))
        self.person5_4.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person5_4.setObjectName(_fromUtf8("person5_4"))
        self.person1_4 = QtGui.QLabel(self.groupDefaultDemo2)
        self.person1_4.setGeometry(QtCore.QRect(10, 10, 56, 31))
        self.person1_4.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1_4.setObjectName(_fromUtf8("person1_4"))
        self.person2_4 = QtGui.QLabel(self.groupDefaultDemo2)
        self.person2_4.setGeometry(QtCore.QRect(90, 90, 56, 31))
        self.person2_4.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_4.setObjectName(_fromUtf8("person2_4"))
        self.person4_4 = QtGui.QLabel(self.groupDefaultDemo2)
        self.person4_4.setGeometry(QtCore.QRect(90, 10, 56, 31))
        self.person4_4.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4_4.setObjectName(_fromUtf8("person4_4"))
        self.person3_4 = QtGui.QLabel(self.groupDefaultDemo2)
        self.person3_4.setGeometry(QtCore.QRect(50, 50, 56, 31))
        self.person3_4.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3_4.setObjectName(_fromUtf8("person3_4"))
        self.groupSacrificeDemo2 = QtGui.QFrame(self.frame_6)
        self.groupSacrificeDemo2.setGeometry(QtCore.QRect(40, 180, 150, 131))
        self.groupSacrificeDemo2.setFrameShape(QtGui.QFrame.NoFrame)
        self.groupSacrificeDemo2.setFrameShadow(QtGui.QFrame.Plain)
        self.groupSacrificeDemo2.setLineWidth(0)
        self.groupSacrificeDemo2.setObjectName(_fromUtf8("groupSacrificeDemo2"))
        self.person5_6 = QtGui.QLabel(self.groupSacrificeDemo2)
        self.person5_6.setGeometry(QtCore.QRect(10, 90, 56, 31))
        self.person5_6.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person5_6.setObjectName(_fromUtf8("person5_6"))
        self.person1_6 = QtGui.QLabel(self.groupSacrificeDemo2)
        self.person1_6.setGeometry(QtCore.QRect(10, 10, 56, 31))
        self.person1_6.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1_6.setObjectName(_fromUtf8("person1_6"))
        self.person2_6 = QtGui.QLabel(self.groupSacrificeDemo2)
        self.person2_6.setGeometry(QtCore.QRect(90, 90, 56, 31))
        self.person2_6.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_6.setObjectName(_fromUtf8("person2_6"))
        self.person4_6 = QtGui.QLabel(self.groupSacrificeDemo2)
        self.person4_6.setGeometry(QtCore.QRect(90, 10, 56, 31))
        self.person4_6.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4_6.setObjectName(_fromUtf8("person4_6"))
        self.person3_6 = QtGui.QLabel(self.groupSacrificeDemo2)
        self.person3_6.setGeometry(QtCore.QRect(50, 50, 56, 31))
        self.person3_6.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3_6.setObjectName(_fromUtf8("person3_6"))
        self.infoLabelSidetrackDemo2 = QtGui.QLabel(self.frame_6)
        self.infoLabelSidetrackDemo2.setGeometry(QtCore.QRect(360, 230, 211, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.infoLabelSidetrackDemo2.setFont(font)
        self.infoLabelSidetrackDemo2.setAutoFillBackground(False)
        self.infoLabelSidetrackDemo2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.infoLabelSidetrackDemo2.setFrameShape(QtGui.QFrame.Box)
        self.infoLabelSidetrackDemo2.setWordWrap(True)
        self.infoLabelSidetrackDemo2.setObjectName(_fromUtf8("infoLabelSidetrackDemo2"))
        self.frame_10 = QtGui.QFrame(self.frame_6)
        self.frame_10.setGeometry(QtCore.QRect(250, 340, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_10.setFont(font)
        self.frame_10.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(255, 255, 255);"))
        self.frame_10.setFrameShape(QtGui.QFrame.Panel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setLineWidth(2)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.label_4 = QtGui.QLabel(self.frame_10)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 56, 13))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.switchSidetrackDemo2.raise_()
        self.switchDefaultDemo2.raise_()
        self.infoLabelSidetrackDemo2.raise_()
        self.frame_10.raise_()
        self.lineSidetrackDemo2.raise_()
        self.groupDefaultDemo2.raise_()
        self.groupSacrificeDemo2.raise_()
        self.ballSidetrackDemo2.raise_()
        self.label_36 = QtGui.QLabel(self.pageSidetrackDemo2)
        self.label_36.setGeometry(QtCore.QRect(310, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_24 = QtGui.QLabel(self.pageSidetrackDemo2)
        self.label_24.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.stackedWidget.addWidget(self.pageSidetrackDemo2)
        self.pageSidetrackExp = QtGui.QWidget()
        self.pageSidetrackExp.setObjectName(_fromUtf8("pageSidetrackExp"))
        self.frame_7 = QtGui.QFrame(self.pageSidetrackExp)
        self.frame_7.setGeometry(QtCore.QRect(30, 70, 611, 391))
        self.frame_7.setStyleSheet(_fromUtf8("background-color: rgb(239, 239, 239);"))
        self.frame_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.ballSidetrackExp = QtGui.QLabel(self.frame_7)
        self.ballSidetrackExp.setGeometry(QtCore.QRect(540, 130, 41, 41))
        self.ballSidetrackExp.setText(_fromUtf8(""))
        self.ballSidetrackExp.setPixmap(QtGui.QPixmap(_fromUtf8("ball.png")))
        self.ballSidetrackExp.setScaledContents(True)
        self.ballSidetrackExp.setObjectName(_fromUtf8("ballSidetrackExp"))
        self.switchButtonExp = QtGui.QPushButton(self.frame_7)
        self.switchButtonExp.setGeometry(QtCore.QRect(250, 340, 110, 32))
        self.switchButtonExp.setAutoFillBackground(False)
        self.switchButtonExp.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.switchButtonExp.setObjectName(_fromUtf8("switchButtonExp"))
        self.lineSidetrackExp = QtGui.QFrame(self.frame_7)
        self.lineSidetrackExp.setGeometry(QtCore.QRect(320, 10, 2, 311))
        self.lineSidetrackExp.setLineWidth(1)
        self.lineSidetrackExp.setMidLineWidth(0)
        self.lineSidetrackExp.setFrameShape(QtGui.QFrame.VLine)
        self.lineSidetrackExp.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineSidetrackExp.setObjectName(_fromUtf8("lineSidetrackExp"))
        self.switchDefaultExp = QtGui.QLabel(self.frame_7)
        self.switchDefaultExp.setGeometry(QtCore.QRect(260, 140, 91, 71))
        self.switchDefaultExp.setText(_fromUtf8(""))
        self.switchDefaultExp.setPixmap(QtGui.QPixmap(_fromUtf8("switch1.png")))
        self.switchDefaultExp.setScaledContents(True)
        self.switchDefaultExp.setObjectName(_fromUtf8("switchDefaultExp"))
        self.switchSidetrackExp = QtGui.QLabel(self.frame_7)
        self.switchSidetrackExp.setGeometry(QtCore.QRect(260, 140, 91, 71))
        self.switchSidetrackExp.setFrameShadow(QtGui.QFrame.Plain)
        self.switchSidetrackExp.setMidLineWidth(0)
        self.switchSidetrackExp.setText(_fromUtf8(""))
        self.switchSidetrackExp.setPixmap(QtGui.QPixmap(_fromUtf8("switch2.png")))
        self.switchSidetrackExp.setScaledContents(True)
        self.switchSidetrackExp.setObjectName(_fromUtf8("switchSidetrackExp"))
        self.groupDefault = QtGui.QFrame(self.frame_7)
        self.groupDefault.setGeometry(QtCore.QRect(40, 20, 171, 161))
        self.groupDefault.setFrameShape(QtGui.QFrame.NoFrame)
        self.groupDefault.setFrameShadow(QtGui.QFrame.Plain)
        self.groupDefault.setLineWidth(0)
        self.groupDefault.setObjectName(_fromUtf8("groupDefault"))
        self.person1_8 = QtGui.QLabel(self.groupDefault)
        self.person1_8.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.person1_8.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1_8.setText(_fromUtf8(""))
        self.person1_8.setPixmap(QtGui.QPixmap(_fromUtf8("Boy1.jpg")))
        self.person1_8.setScaledContents(True)
        self.person1_8.setObjectName(_fromUtf8("person1_8"))
        self.person2_9 = QtGui.QLabel(self.groupDefault)
        self.person2_9.setGeometry(QtCore.QRect(110, 100, 50, 50))
        self.person2_9.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_9.setText(_fromUtf8(""))
        self.person2_9.setPixmap(QtGui.QPixmap(_fromUtf8("Girl3.jpg")))
        self.person2_9.setScaledContents(True)
        self.person2_9.setObjectName(_fromUtf8("person2_9"))
        self.person4_8 = QtGui.QLabel(self.groupDefault)
        self.person4_8.setGeometry(QtCore.QRect(110, 10, 50, 50))
        self.person4_8.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4_8.setText(_fromUtf8(""))
        self.person4_8.setPixmap(QtGui.QPixmap(_fromUtf8("Boy4.jpg")))
        self.person4_8.setScaledContents(True)
        self.person4_8.setObjectName(_fromUtf8("person4_8"))
        self.person3_8 = QtGui.QLabel(self.groupDefault)
        self.person3_8.setGeometry(QtCore.QRect(60, 50, 50, 50))
        self.person3_8.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3_8.setText(_fromUtf8(""))
        self.person3_8.setPixmap(QtGui.QPixmap(_fromUtf8("Girl2.jpg")))
        self.person3_8.setScaledContents(True)
        self.person3_8.setObjectName(_fromUtf8("person3_8"))
        self.person2_10 = QtGui.QLabel(self.groupDefault)
        self.person2_10.setGeometry(QtCore.QRect(10, 100, 50, 50))
        self.person2_10.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_10.setText(_fromUtf8(""))
        self.person2_10.setPixmap(QtGui.QPixmap(_fromUtf8("Boy3.jpg")))
        self.person2_10.setScaledContents(True)
        self.person2_10.setObjectName(_fromUtf8("person2_10"))
        self.personSidetrack = QtGui.QLabel(self.frame_7)
        self.personSidetrack.setGeometry(QtCore.QRect(90, 240, 50, 50))
        self.personSidetrack.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.personSidetrack.setText(_fromUtf8(""))
        self.personSidetrack.setPixmap(QtGui.QPixmap(_fromUtf8("Girl1.jpg")))
        self.personSidetrack.setScaledContents(True)
        self.personSidetrack.setObjectName(_fromUtf8("personSidetrack"))
        self.switchSidetrackExp.raise_()
        self.switchDefaultExp.raise_()
        self.switchButtonExp.raise_()
        self.groupDefault.raise_()
        self.personSidetrack.raise_()
        self.lineSidetrackExp.raise_()
        self.ballSidetrackExp.raise_()
        self.continueSidetrackExpButton = QtGui.QPushButton(self.pageSidetrackExp)
        self.continueSidetrackExpButton.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.continueSidetrackExpButton.setFont(font)
        self.continueSidetrackExpButton.setAutoFillBackground(False)
        self.continueSidetrackExpButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.continueSidetrackExpButton.setObjectName(_fromUtf8("continueSidetrackExpButton"))
        self.label_25 = QtGui.QLabel(self.pageSidetrackExp)
        self.label_25.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.stackedWidget.addWidget(self.pageSidetrackExp)
        self.pageSidetrackQuestion = QtGui.QWidget()
        self.pageSidetrackQuestion.setObjectName(_fromUtf8("pageSidetrackQuestion"))
        self.confirmSidetrackRatingButton = QtGui.QPushButton(self.pageSidetrackQuestion)
        self.confirmSidetrackRatingButton.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.confirmSidetrackRatingButton.setFont(font)
        self.confirmSidetrackRatingButton.setAutoFillBackground(False)
        self.confirmSidetrackRatingButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.confirmSidetrackRatingButton.setObjectName(_fromUtf8("confirmSidetrackRatingButton"))
        self.label_16 = QtGui.QLabel(self.pageSidetrackQuestion)
        self.label_16.setGeometry(QtCore.QRect(210, 60, 291, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.frame_4 = QtGui.QFrame(self.pageSidetrackQuestion)
        self.frame_4.setGeometry(QtCore.QRect(210, 140, 241, 291))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.radioButton = QtGui.QRadioButton(self.frame_4)
        self.radioButton.setGeometry(QtCore.QRect(20, 10, 141, 18))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.sidetrackButtonGroup = QtGui.QButtonGroup(trolleyWindow)
        self.sidetrackButtonGroup.setObjectName(_fromUtf8("sidetrackButtonGroup"))
        self.sidetrackButtonGroup.addButton(self.radioButton)
        self.radioButton_3 = QtGui.QRadioButton(self.frame_4)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 70, 141, 18))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.sidetrackButtonGroup.addButton(self.radioButton_3)
        self.radioButton_6 = QtGui.QRadioButton(self.frame_4)
        self.radioButton_6.setGeometry(QtCore.QRect(20, 160, 141, 18))
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.sidetrackButtonGroup.addButton(self.radioButton_6)
        self.radioButton_5 = QtGui.QRadioButton(self.frame_4)
        self.radioButton_5.setGeometry(QtCore.QRect(20, 130, 141, 18))
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.sidetrackButtonGroup.addButton(self.radioButton_5)
        self.radioButton_4 = QtGui.QRadioButton(self.frame_4)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 100, 141, 18))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.sidetrackButtonGroup.addButton(self.radioButton_4)
        self.radioButton_8 = QtGui.QRadioButton(self.frame_4)
        self.radioButton_8.setGeometry(QtCore.QRect(20, 220, 141, 18))
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.sidetrackButtonGroup.addButton(self.radioButton_8)
        self.radioButton_2 = QtGui.QRadioButton(self.frame_4)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 40, 141, 18))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.sidetrackButtonGroup.addButton(self.radioButton_2)
        self.radioButton_7 = QtGui.QRadioButton(self.frame_4)
        self.radioButton_7.setGeometry(QtCore.QRect(20, 190, 141, 18))
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.sidetrackButtonGroup.addButton(self.radioButton_7)
        self.radioButton_9 = QtGui.QRadioButton(self.frame_4)
        self.radioButton_9.setGeometry(QtCore.QRect(20, 250, 141, 18))
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.sidetrackButtonGroup.addButton(self.radioButton_9)
        self.label_DefWrong = QtGui.QLabel(self.frame_4)
        self.label_DefWrong.setGeometry(QtCore.QRect(60, 10, 111, 16))
        self.label_DefWrong.setObjectName(_fromUtf8("label_DefWrong"))
        self.label_DefWright = QtGui.QLabel(self.frame_4)
        self.label_DefWright.setGeometry(QtCore.QRect(60, 250, 111, 16))
        self.label_DefWright.setObjectName(_fromUtf8("label_DefWright"))
        self.label_Neutral = QtGui.QLabel(self.frame_4)
        self.label_Neutral.setGeometry(QtCore.QRect(60, 130, 111, 16))
        self.label_Neutral.setObjectName(_fromUtf8("label_Neutral"))
        self.labelSidetrackRatingError = QtGui.QLabel(self.pageSidetrackQuestion)
        self.labelSidetrackRatingError.setGeometry(QtCore.QRect(470, 240, 161, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelSidetrackRatingError.setFont(font)
        self.labelSidetrackRatingError.setStyleSheet(_fromUtf8("color: rgb(252, 7, 22);"))
        self.labelSidetrackRatingError.setWordWrap(True)
        self.labelSidetrackRatingError.setObjectName(_fromUtf8("labelSidetrackRatingError"))
        self.label_26 = QtGui.QLabel(self.pageSidetrackQuestion)
        self.label_26.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_26.setText(_fromUtf8(""))
        self.label_26.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.frame_4.raise_()
        self.confirmSidetrackRatingButton.raise_()
        self.label_16.raise_()
        self.labelSidetrackRatingError.raise_()
        self.label_26.raise_()
        self.stackedWidget.addWidget(self.pageSidetrackQuestion)
        self.pageFootbridgeDemo1 = QtGui.QWidget()
        self.pageFootbridgeDemo1.setObjectName(_fromUtf8("pageFootbridgeDemo1"))
        self.frame_2 = QtGui.QFrame(self.pageFootbridgeDemo1)
        self.frame_2.setGeometry(QtCore.QRect(30, 70, 611, 391))
        self.frame_2.setStyleSheet(_fromUtf8("background-color: rgb(239, 239, 239);"))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.ballFootbridgeDemo1 = QtGui.QLabel(self.frame_2)
        self.ballFootbridgeDemo1.setGeometry(QtCore.QRect(540, 130, 41, 41))
        self.ballFootbridgeDemo1.setText(_fromUtf8(""))
        self.ballFootbridgeDemo1.setPixmap(QtGui.QPixmap(_fromUtf8("ball.png")))
        self.ballFootbridgeDemo1.setScaledContents(True)
        self.ballFootbridgeDemo1.setObjectName(_fromUtf8("ballFootbridgeDemo1"))
        self.groupFootbridgeDemo1 = QtGui.QFrame(self.frame_2)
        self.groupFootbridgeDemo1.setGeometry(QtCore.QRect(10, 80, 150, 131))
        self.groupFootbridgeDemo1.setFrameShape(QtGui.QFrame.NoFrame)
        self.groupFootbridgeDemo1.setFrameShadow(QtGui.QFrame.Plain)
        self.groupFootbridgeDemo1.setLineWidth(0)
        self.groupFootbridgeDemo1.setObjectName(_fromUtf8("groupFootbridgeDemo1"))
        self.person5_2 = QtGui.QLabel(self.groupFootbridgeDemo1)
        self.person5_2.setGeometry(QtCore.QRect(10, 90, 56, 31))
        self.person5_2.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person5_2.setObjectName(_fromUtf8("person5_2"))
        self.person1_2 = QtGui.QLabel(self.groupFootbridgeDemo1)
        self.person1_2.setGeometry(QtCore.QRect(10, 10, 56, 31))
        self.person1_2.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1_2.setObjectName(_fromUtf8("person1_2"))
        self.person2_2 = QtGui.QLabel(self.groupFootbridgeDemo1)
        self.person2_2.setGeometry(QtCore.QRect(90, 90, 56, 31))
        self.person2_2.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_2.setObjectName(_fromUtf8("person2_2"))
        self.person4_2 = QtGui.QLabel(self.groupFootbridgeDemo1)
        self.person4_2.setGeometry(QtCore.QRect(90, 10, 56, 31))
        self.person4_2.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4_2.setObjectName(_fromUtf8("person4_2"))
        self.person3_2 = QtGui.QLabel(self.groupFootbridgeDemo1)
        self.person3_2.setGeometry(QtCore.QRect(50, 50, 56, 31))
        self.person3_2.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3_2.setObjectName(_fromUtf8("person3_2"))
        self.groupSacrificeFootbridgeDemo1 = QtGui.QFrame(self.frame_2)
        self.groupSacrificeFootbridgeDemo1.setGeometry(QtCore.QRect(10, 240, 150, 131))
        self.groupSacrificeFootbridgeDemo1.setFrameShape(QtGui.QFrame.NoFrame)
        self.groupSacrificeFootbridgeDemo1.setFrameShadow(QtGui.QFrame.Plain)
        self.groupSacrificeFootbridgeDemo1.setLineWidth(0)
        self.groupSacrificeFootbridgeDemo1.setObjectName(_fromUtf8("groupSacrificeFootbridgeDemo1"))
        self.person5_5 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo1)
        self.person5_5.setGeometry(QtCore.QRect(10, 90, 56, 31))
        self.person5_5.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person5_5.setObjectName(_fromUtf8("person5_5"))
        self.person1_5 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo1)
        self.person1_5.setGeometry(QtCore.QRect(10, 10, 56, 31))
        self.person1_5.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1_5.setObjectName(_fromUtf8("person1_5"))
        self.person2_5 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo1)
        self.person2_5.setGeometry(QtCore.QRect(90, 90, 56, 31))
        self.person2_5.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_5.setObjectName(_fromUtf8("person2_5"))
        self.person4_5 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo1)
        self.person4_5.setGeometry(QtCore.QRect(90, 10, 56, 31))
        self.person4_5.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4_5.setObjectName(_fromUtf8("person4_5"))
        self.person3_5 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo1)
        self.person3_5.setGeometry(QtCore.QRect(50, 50, 56, 31))
        self.person3_5.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3_5.setObjectName(_fromUtf8("person3_5"))
        self.infoLabelFootbridgeDemo1 = QtGui.QLabel(self.frame_2)
        self.infoLabelFootbridgeDemo1.setGeometry(QtCore.QRect(360, 230, 211, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.infoLabelFootbridgeDemo1.setFont(font)
        self.infoLabelFootbridgeDemo1.setAutoFillBackground(False)
        self.infoLabelFootbridgeDemo1.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.infoLabelFootbridgeDemo1.setFrameShape(QtGui.QFrame.Box)
        self.infoLabelFootbridgeDemo1.setWordWrap(True)
        self.infoLabelFootbridgeDemo1.setObjectName(_fromUtf8("infoLabelFootbridgeDemo1"))
        self.lineFootbridgeDemo1 = QtGui.QFrame(self.frame_2)
        self.lineFootbridgeDemo1.setGeometry(QtCore.QRect(320, 10, 2, 331))
        self.lineFootbridgeDemo1.setLineWidth(1)
        self.lineFootbridgeDemo1.setMidLineWidth(0)
        self.lineFootbridgeDemo1.setFrameShape(QtGui.QFrame.VLine)
        self.lineFootbridgeDemo1.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineFootbridgeDemo1.setObjectName(_fromUtf8("lineFootbridgeDemo1"))
        self.lineFootbridgeDemo1.raise_()
        self.groupFootbridgeDemo1.raise_()
        self.groupSacrificeFootbridgeDemo1.raise_()
        self.infoLabelFootbridgeDemo1.raise_()
        self.ballFootbridgeDemo1.raise_()
        self.label_7 = QtGui.QLabel(self.pageFootbridgeDemo1)
        self.label_7.setGeometry(QtCore.QRect(310, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.continueFootbridgeDemo1Button = QtGui.QPushButton(self.pageFootbridgeDemo1)
        self.continueFootbridgeDemo1Button.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.continueFootbridgeDemo1Button.setFont(font)
        self.continueFootbridgeDemo1Button.setAutoFillBackground(False)
        self.continueFootbridgeDemo1Button.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.continueFootbridgeDemo1Button.setObjectName(_fromUtf8("continueFootbridgeDemo1Button"))
        self.label_27 = QtGui.QLabel(self.pageFootbridgeDemo1)
        self.label_27.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.stackedWidget.addWidget(self.pageFootbridgeDemo1)
        self.pageFootbridgeDemo2 = QtGui.QWidget()
        self.pageFootbridgeDemo2.setObjectName(_fromUtf8("pageFootbridgeDemo2"))
        self.continueFootbridgeDemo2Button = QtGui.QPushButton(self.pageFootbridgeDemo2)
        self.continueFootbridgeDemo2Button.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.continueFootbridgeDemo2Button.setFont(font)
        self.continueFootbridgeDemo2Button.setAutoFillBackground(False)
        self.continueFootbridgeDemo2Button.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.continueFootbridgeDemo2Button.setObjectName(_fromUtf8("continueFootbridgeDemo2Button"))
        self.label_11 = QtGui.QLabel(self.pageFootbridgeDemo2)
        self.label_11.setGeometry(QtCore.QRect(310, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.frame_8 = QtGui.QFrame(self.pageFootbridgeDemo2)
        self.frame_8.setGeometry(QtCore.QRect(30, 70, 611, 391))
        self.frame_8.setStyleSheet(_fromUtf8("background-color: rgb(239, 239, 239);"))
        self.frame_8.setFrameShape(QtGui.QFrame.Box)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.ballFootbridgeDemo2 = QtGui.QLabel(self.frame_8)
        self.ballFootbridgeDemo2.setGeometry(QtCore.QRect(540, 130, 41, 41))
        self.ballFootbridgeDemo2.setText(_fromUtf8(""))
        self.ballFootbridgeDemo2.setPixmap(QtGui.QPixmap(_fromUtf8("ball.png")))
        self.ballFootbridgeDemo2.setScaledContents(True)
        self.ballFootbridgeDemo2.setObjectName(_fromUtf8("ballFootbridgeDemo2"))
        self.lineFootbridgeDemo2 = QtGui.QFrame(self.frame_8)
        self.lineFootbridgeDemo2.setGeometry(QtCore.QRect(320, 10, 2, 331))
        self.lineFootbridgeDemo2.setLineWidth(1)
        self.lineFootbridgeDemo2.setMidLineWidth(0)
        self.lineFootbridgeDemo2.setFrameShape(QtGui.QFrame.VLine)
        self.lineFootbridgeDemo2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineFootbridgeDemo2.setObjectName(_fromUtf8("lineFootbridgeDemo2"))
        self.groupFootbridgeDemo2 = QtGui.QFrame(self.frame_8)
        self.groupFootbridgeDemo2.setGeometry(QtCore.QRect(10, 80, 150, 131))
        self.groupFootbridgeDemo2.setFrameShape(QtGui.QFrame.NoFrame)
        self.groupFootbridgeDemo2.setFrameShadow(QtGui.QFrame.Plain)
        self.groupFootbridgeDemo2.setLineWidth(0)
        self.groupFootbridgeDemo2.setObjectName(_fromUtf8("groupFootbridgeDemo2"))
        self.person5_12 = QtGui.QLabel(self.groupFootbridgeDemo2)
        self.person5_12.setGeometry(QtCore.QRect(10, 90, 56, 31))
        self.person5_12.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person5_12.setObjectName(_fromUtf8("person5_12"))
        self.person1_12 = QtGui.QLabel(self.groupFootbridgeDemo2)
        self.person1_12.setGeometry(QtCore.QRect(10, 10, 56, 31))
        self.person1_12.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1_12.setObjectName(_fromUtf8("person1_12"))
        self.person2_13 = QtGui.QLabel(self.groupFootbridgeDemo2)
        self.person2_13.setGeometry(QtCore.QRect(90, 90, 56, 31))
        self.person2_13.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_13.setObjectName(_fromUtf8("person2_13"))
        self.person4_12 = QtGui.QLabel(self.groupFootbridgeDemo2)
        self.person4_12.setGeometry(QtCore.QRect(90, 10, 56, 31))
        self.person4_12.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4_12.setObjectName(_fromUtf8("person4_12"))
        self.person3_12 = QtGui.QLabel(self.groupFootbridgeDemo2)
        self.person3_12.setGeometry(QtCore.QRect(50, 50, 56, 31))
        self.person3_12.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3_12.setObjectName(_fromUtf8("person3_12"))
        self.groupSacrificeFootbridgeDemo2 = QtGui.QFrame(self.frame_8)
        self.groupSacrificeFootbridgeDemo2.setGeometry(QtCore.QRect(10, 240, 150, 131))
        self.groupSacrificeFootbridgeDemo2.setFrameShape(QtGui.QFrame.NoFrame)
        self.groupSacrificeFootbridgeDemo2.setFrameShadow(QtGui.QFrame.Plain)
        self.groupSacrificeFootbridgeDemo2.setLineWidth(0)
        self.groupSacrificeFootbridgeDemo2.setObjectName(_fromUtf8("groupSacrificeFootbridgeDemo2"))
        self.person5_13 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo2)
        self.person5_13.setGeometry(QtCore.QRect(10, 90, 56, 31))
        self.person5_13.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person5_13.setObjectName(_fromUtf8("person5_13"))
        self.person1_13 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo2)
        self.person1_13.setGeometry(QtCore.QRect(10, 10, 56, 31))
        self.person1_13.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1_13.setObjectName(_fromUtf8("person1_13"))
        self.person2_14 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo2)
        self.person2_14.setGeometry(QtCore.QRect(90, 90, 56, 31))
        self.person2_14.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_14.setObjectName(_fromUtf8("person2_14"))
        self.person4_13 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo2)
        self.person4_13.setGeometry(QtCore.QRect(90, 10, 56, 31))
        self.person4_13.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4_13.setObjectName(_fromUtf8("person4_13"))
        self.person3_13 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo2)
        self.person3_13.setGeometry(QtCore.QRect(50, 50, 56, 31))
        self.person3_13.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3_13.setObjectName(_fromUtf8("person3_13"))
        self.infoLabelFootbridgeDemo2 = QtGui.QLabel(self.frame_8)
        self.infoLabelFootbridgeDemo2.setGeometry(QtCore.QRect(360, 230, 211, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.infoLabelFootbridgeDemo2.setFont(font)
        self.infoLabelFootbridgeDemo2.setAutoFillBackground(False)
        self.infoLabelFootbridgeDemo2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.infoLabelFootbridgeDemo2.setFrameShape(QtGui.QFrame.Box)
        self.infoLabelFootbridgeDemo2.setWordWrap(True)
        self.infoLabelFootbridgeDemo2.setObjectName(_fromUtf8("infoLabelFootbridgeDemo2"))
        self.groupSacrificeFootbridgeDemo2_2 = QtGui.QFrame(self.frame_8)
        self.groupSacrificeFootbridgeDemo2_2.setGeometry(QtCore.QRect(160, 80, 150, 131))
        self.groupSacrificeFootbridgeDemo2_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.groupSacrificeFootbridgeDemo2_2.setFrameShadow(QtGui.QFrame.Plain)
        self.groupSacrificeFootbridgeDemo2_2.setLineWidth(0)
        self.groupSacrificeFootbridgeDemo2_2.setObjectName(_fromUtf8("groupSacrificeFootbridgeDemo2_2"))
        self.person5_15 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo2_2)
        self.person5_15.setGeometry(QtCore.QRect(10, 90, 56, 31))
        self.person5_15.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person5_15.setObjectName(_fromUtf8("person5_15"))
        self.person1_15 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo2_2)
        self.person1_15.setGeometry(QtCore.QRect(10, 10, 56, 31))
        self.person1_15.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1_15.setObjectName(_fromUtf8("person1_15"))
        self.person2_16 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo2_2)
        self.person2_16.setGeometry(QtCore.QRect(90, 90, 56, 31))
        self.person2_16.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_16.setObjectName(_fromUtf8("person2_16"))
        self.person4_15 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo2_2)
        self.person4_15.setGeometry(QtCore.QRect(90, 10, 56, 31))
        self.person4_15.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4_15.setObjectName(_fromUtf8("person4_15"))
        self.person3_15 = QtGui.QLabel(self.groupSacrificeFootbridgeDemo2_2)
        self.person3_15.setGeometry(QtCore.QRect(50, 50, 56, 31))
        self.person3_15.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3_15.setObjectName(_fromUtf8("person3_15"))
        self.lineFootbridgeDemo2.raise_()
        self.groupFootbridgeDemo2.raise_()
        self.groupSacrificeFootbridgeDemo2.raise_()
        self.infoLabelFootbridgeDemo2.raise_()
        self.groupSacrificeFootbridgeDemo2_2.raise_()
        self.ballFootbridgeDemo2.raise_()
        self.label_28 = QtGui.QLabel(self.pageFootbridgeDemo2)
        self.label_28.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_28.setText(_fromUtf8(""))
        self.label_28.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.stackedWidget.addWidget(self.pageFootbridgeDemo2)
        self.pageFootbridgeExp = QtGui.QWidget()
        self.pageFootbridgeExp.setObjectName(_fromUtf8("pageFootbridgeExp"))
        self.frame_3 = QtGui.QFrame(self.pageFootbridgeExp)
        self.frame_3.setGeometry(QtCore.QRect(30, 70, 611, 391))
        self.frame_3.setStyleSheet(_fromUtf8("background-color: rgb(239, 239, 239);"))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.ballFootbridgeExp = QtGui.QLabel(self.frame_3)
        self.ballFootbridgeExp.setGeometry(QtCore.QRect(540, 130, 41, 41))
        self.ballFootbridgeExp.setText(_fromUtf8(""))
        self.ballFootbridgeExp.setPixmap(QtGui.QPixmap(_fromUtf8("ball.png")))
        self.ballFootbridgeExp.setScaledContents(True)
        self.ballFootbridgeExp.setObjectName(_fromUtf8("ballFootbridgeExp"))
        self.lineFootbridgeExp = QtGui.QFrame(self.frame_3)
        self.lineFootbridgeExp.setGeometry(QtCore.QRect(320, 10, 2, 331))
        self.lineFootbridgeExp.setLineWidth(1)
        self.lineFootbridgeExp.setMidLineWidth(0)
        self.lineFootbridgeExp.setFrameShape(QtGui.QFrame.VLine)
        self.lineFootbridgeExp.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineFootbridgeExp.setObjectName(_fromUtf8("lineFootbridgeExp"))
        self.groupFootbridgeExp = QtGui.QFrame(self.frame_3)
        self.groupFootbridgeExp.setGeometry(QtCore.QRect(10, 80, 171, 151))
        self.groupFootbridgeExp.setFrameShape(QtGui.QFrame.NoFrame)
        self.groupFootbridgeExp.setFrameShadow(QtGui.QFrame.Plain)
        self.groupFootbridgeExp.setLineWidth(0)
        self.groupFootbridgeExp.setObjectName(_fromUtf8("groupFootbridgeExp"))
        self.person5_7 = QtGui.QLabel(self.groupFootbridgeExp)
        self.person5_7.setGeometry(QtCore.QRect(10, 90, 50, 50))
        self.person5_7.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person5_7.setText(_fromUtf8(""))
        self.person5_7.setPixmap(QtGui.QPixmap(_fromUtf8("Girl6.jpg")))
        self.person5_7.setScaledContents(True)
        self.person5_7.setObjectName(_fromUtf8("person5_7"))
        self.person1_7 = QtGui.QLabel(self.groupFootbridgeExp)
        self.person1_7.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.person1_7.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person1_7.setText(_fromUtf8(""))
        self.person1_7.setPixmap(QtGui.QPixmap(_fromUtf8("Girl4.jpg")))
        self.person1_7.setScaledContents(True)
        self.person1_7.setObjectName(_fromUtf8("person1_7"))
        self.person2_7 = QtGui.QLabel(self.groupFootbridgeExp)
        self.person2_7.setGeometry(QtCore.QRect(110, 90, 50, 50))
        self.person2_7.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person2_7.setText(_fromUtf8(""))
        self.person2_7.setPixmap(QtGui.QPixmap(_fromUtf8("Boy6.jpg")))
        self.person2_7.setScaledContents(True)
        self.person2_7.setObjectName(_fromUtf8("person2_7"))
        self.person4_7 = QtGui.QLabel(self.groupFootbridgeExp)
        self.person4_7.setGeometry(QtCore.QRect(110, 10, 50, 50))
        self.person4_7.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person4_7.setText(_fromUtf8(""))
        self.person4_7.setPixmap(QtGui.QPixmap(_fromUtf8("Girl5.jpg")))
        self.person4_7.setScaledContents(True)
        self.person4_7.setObjectName(_fromUtf8("person4_7"))
        self.person3_7 = QtGui.QLabel(self.groupFootbridgeExp)
        self.person3_7.setGeometry(QtCore.QRect(60, 50, 50, 50))
        self.person3_7.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.person3_7.setText(_fromUtf8(""))
        self.person3_7.setPixmap(QtGui.QPixmap(_fromUtf8("Boy5.jpg")))
        self.person3_7.setScaledContents(True)
        self.person3_7.setObjectName(_fromUtf8("person3_7"))
        self.personFootbridgeSacrifice2 = QtGui.QLabel(self.frame_3)
        self.personFootbridgeSacrifice2.setGeometry(QtCore.QRect(270, 130, 51, 50))
        self.personFootbridgeSacrifice2.setStyleSheet(_fromUtf8("background-color: rgb(9, 9, 9);"))
        self.personFootbridgeSacrifice2.setText(_fromUtf8(""))
        self.personFootbridgeSacrifice2.setPixmap(QtGui.QPixmap(_fromUtf8("Boy2.png")))
        self.personFootbridgeSacrifice2.setScaledContents(True)
        self.personFootbridgeSacrifice2.setObjectName(_fromUtf8("personFootbridgeSacrifice2"))
        self.personFootbridgeSacrifice1 = QtGui.QLabel(self.frame_3)
        self.personFootbridgeSacrifice1.setGeometry(QtCore.QRect(70, 260, 50, 50))
        self.personFootbridgeSacrifice1.setWordWrap(True)
        self.personFootbridgeSacrifice1.setObjectName(_fromUtf8("personFootbridgeSacrifice1"))
        self.personFootbridgeSacrifice1.raise_()
        self.lineFootbridgeExp.raise_()
        self.groupFootbridgeExp.raise_()
        self.personFootbridgeSacrifice2.raise_()
        self.ballFootbridgeExp.raise_()
        self.continueFootbridgeExpButton = QtGui.QPushButton(self.pageFootbridgeExp)
        self.continueFootbridgeExpButton.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.continueFootbridgeExpButton.setFont(font)
        self.continueFootbridgeExpButton.setAutoFillBackground(False)
        self.continueFootbridgeExpButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.continueFootbridgeExpButton.setObjectName(_fromUtf8("continueFootbridgeExpButton"))
        self.label_29 = QtGui.QLabel(self.pageFootbridgeExp)
        self.label_29.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_29.setText(_fromUtf8(""))
        self.label_29.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.stackedWidget.addWidget(self.pageFootbridgeExp)
        self.pageFootbridgeQuestion = QtGui.QWidget()
        self.pageFootbridgeQuestion.setObjectName(_fromUtf8("pageFootbridgeQuestion"))
        self.confirmFootbridgeRatingButton = QtGui.QPushButton(self.pageFootbridgeQuestion)
        self.confirmFootbridgeRatingButton.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.confirmFootbridgeRatingButton.setFont(font)
        self.confirmFootbridgeRatingButton.setAutoFillBackground(False)
        self.confirmFootbridgeRatingButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.confirmFootbridgeRatingButton.setObjectName(_fromUtf8("confirmFootbridgeRatingButton"))
        self.frame_5 = QtGui.QFrame(self.pageFootbridgeQuestion)
        self.frame_5.setGeometry(QtCore.QRect(210, 140, 241, 291))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.frame_5.setFont(font)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.radioButton_10 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_10.setGeometry(QtCore.QRect(20, 10, 141, 18))
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.footbridgeButtonGroup = QtGui.QButtonGroup(trolleyWindow)
        self.footbridgeButtonGroup.setObjectName(_fromUtf8("footbridgeButtonGroup"))
        self.footbridgeButtonGroup.addButton(self.radioButton_10)
        self.radioButton_11 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_11.setGeometry(QtCore.QRect(20, 70, 141, 18))
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.footbridgeButtonGroup.addButton(self.radioButton_11)
        self.radioButton_12 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_12.setGeometry(QtCore.QRect(20, 160, 141, 18))
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.footbridgeButtonGroup.addButton(self.radioButton_12)
        self.radioButton_13 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_13.setGeometry(QtCore.QRect(20, 130, 141, 18))
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.footbridgeButtonGroup.addButton(self.radioButton_13)
        self.radioButton_14 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_14.setGeometry(QtCore.QRect(20, 100, 141, 18))
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.footbridgeButtonGroup.addButton(self.radioButton_14)
        self.radioButton_15 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_15.setGeometry(QtCore.QRect(20, 220, 141, 18))
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.footbridgeButtonGroup.addButton(self.radioButton_15)
        self.radioButton_16 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_16.setGeometry(QtCore.QRect(20, 40, 141, 18))
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.footbridgeButtonGroup.addButton(self.radioButton_16)
        self.radioButton_17 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_17.setGeometry(QtCore.QRect(20, 190, 141, 18))
        self.radioButton_17.setObjectName(_fromUtf8("radioButton_17"))
        self.footbridgeButtonGroup.addButton(self.radioButton_17)
        self.radioButton_18 = QtGui.QRadioButton(self.frame_5)
        self.radioButton_18.setGeometry(QtCore.QRect(20, 250, 141, 18))
        self.radioButton_18.setObjectName(_fromUtf8("radioButton_18"))
        self.footbridgeButtonGroup.addButton(self.radioButton_18)
        self.label_DefWrong_2 = QtGui.QLabel(self.frame_5)
        self.label_DefWrong_2.setGeometry(QtCore.QRect(70, 10, 111, 16))
        self.label_DefWrong_2.setObjectName(_fromUtf8("label_DefWrong_2"))
        self.label_DefWright_2 = QtGui.QLabel(self.frame_5)
        self.label_DefWright_2.setGeometry(QtCore.QRect(70, 250, 111, 16))
        self.label_DefWright_2.setObjectName(_fromUtf8("label_DefWright_2"))
        self.label_Neutral_2 = QtGui.QLabel(self.frame_5)
        self.label_Neutral_2.setGeometry(QtCore.QRect(70, 130, 111, 16))
        self.label_Neutral_2.setObjectName(_fromUtf8("label_Neutral_2"))
        self.label_17 = QtGui.QLabel(self.pageFootbridgeQuestion)
        self.label_17.setGeometry(QtCore.QRect(210, 60, 281, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.labelFootbridgeRatingError = QtGui.QLabel(self.pageFootbridgeQuestion)
        self.labelFootbridgeRatingError.setGeometry(QtCore.QRect(470, 240, 151, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelFootbridgeRatingError.setFont(font)
        self.labelFootbridgeRatingError.setStyleSheet(_fromUtf8("color: rgb(252, 7, 22);"))
        self.labelFootbridgeRatingError.setWordWrap(True)
        self.labelFootbridgeRatingError.setObjectName(_fromUtf8("labelFootbridgeRatingError"))
        self.label_30 = QtGui.QLabel(self.pageFootbridgeQuestion)
        self.label_30.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_30.setText(_fromUtf8(""))
        self.label_30.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.stackedWidget.addWidget(self.pageFootbridgeQuestion)
        self.pageDebrief = QtGui.QWidget()
        self.pageDebrief.setObjectName(_fromUtf8("pageDebrief"))
        self.endButton = QtGui.QPushButton(self.pageDebrief)
        self.endButton.setGeometry(QtCore.QRect(280, 470, 110, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.endButton.setFont(font)
        self.endButton.setAutoFillBackground(False)
        self.endButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.endButton.setObjectName(_fromUtf8("endButton"))
        self.label_18 = QtGui.QLabel(self.pageDebrief)
        self.label_18.setGeometry(QtCore.QRect(50, 300, 551, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_20 = QtGui.QLabel(self.pageDebrief)
        self.label_20.setGeometry(QtCore.QRect(50, 90, 561, 191))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_31 = QtGui.QLabel(self.pageDebrief)
        self.label_31.setGeometry(QtCore.QRect(0, -20, 131, 91))
        self.label_31.setText(_fromUtf8(""))
        self.label_31.setPixmap(QtGui.QPixmap(_fromUtf8("ucl-logo.jpg")))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.stackedWidget.addWidget(self.pageDebrief)
        trolleyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(trolleyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 854, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        trolleyWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(trolleyWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        trolleyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(trolleyWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(trolleyWindow)

    def retranslateUi(self, trolleyWindow):
        trolleyWindow.setWindowTitle(_translate("trolleyWindow", "MainWindow", None))
        self.consentContinueButton.setText(_translate("trolleyWindow", "Continue", None))
        self.consentInfo.setText(_translate("trolleyWindow", "We would like to invite you to participate in this experiment directed by researchers at UCL. You should only participate if you want to; choosing not to take part will not disadvantage you in any way. Before you decide whether you want to take part, it is important for you to read the following information carefully and discuss it with others if you wish. Ask us if there is anything that is not clear or if you would like more information. ", None))
        self.consentInfo_2.setText(_translate("trolleyWindow", "Please read the information below and tick the box below to give consent to participate in this experiment", None))
        self.consentInfo_4.setText(_translate("trolleyWindow", "By ticking the box below you agree that you have: \n"
" - read the information above \n"
" - had an opportunity to ask questions and discuss the study \n"
" - received satisfactory answers to all my questions or have been advised of an individual to contact \n"
" - understood that I have the right to withdraw at any stage simply by closing the experiment window\n"
" - understood that I consent to the processing of my personal information for the purposes of this study only and that any such information will be treated as strictly confidential and handled in accordance with the provisions of the Data Protection Act 1998 \n"
" - understood that, by clicking ‘Continue’, I consent to participate in this study ", None))
        self.consentInfo_3.setText(_translate("trolleyWindow", "In this study you will be asked to read a short description of a task and then choose your preferred option. Only UCL researchers working with Prof Jeremy Bentham will analyse these data. It is up to you to decide whether or not to take part. If you decide to take part you will be given this information sheet to keep and be asked to sign a consent form. If you decide to take part you are still free to withdraw at any time and without giving a reason. You may wish to print this information for your records.", None))
        self.consentBox.setText(_translate("trolleyWindow", "Tick this box to confirm you consent to participate", None))
        self.demogContinueButton.setText(_translate("trolleyWindow", "Continue", None))
        self.labelErrorGender.setText(_translate("trolleyWindow", "You must select your gender", None))
        self.labelErrorAge.setText(_translate("trolleyWindow", "You need to be over 18 to take part in this experiment", None))
        self.labelErrorEducation.setText(_translate("trolleyWindow", "You must select your highest education level", None))
        self.Education.setItemText(1, _translate("trolleyWindow", "Upper Secondary", None))
        self.Education.setItemText(2, _translate("trolleyWindow", "Post-secondary", None))
        self.Education.setItemText(3, _translate("trolleyWindow", "Bachelor\'s or equivalent", None))
        self.Education.setItemText(4, _translate("trolleyWindow", "Master\'s or equivalent", None))
        self.Education.setItemText(5, _translate("trolleyWindow", "Doctoral or equivalent", None))
        self.labelEducation.setText(_translate("trolleyWindow", "Education Level", None))
        self.labelDemog.setText(_translate("trolleyWindow", "Please enter some details about yourself and then click \'Continue\'", None))
        self.Male.setText(_translate("trolleyWindow", "Male", None))
        self.Female.setText(_translate("trolleyWindow", "Female", None))
        self.labelGender.setText(_translate("trolleyWindow", "Gender", None))
        self.labelAge.setText(_translate("trolleyWindow", "Age", None))
        self.brochureContinueButton.setText(_translate("trolleyWindow", "Continue", None))
        self.label_12.setText(_translate("trolleyWindow", "Canaan Children\'s Home", None))
        self.instructions_4.setText(_translate("trolleyWindow", "The 12 children below are all orphans living at the Canaan Children\'s Home in Northern Uganda. Every child from the home has been given a sum of money enough to buy them one meal.", None))
        self.instructContinueButton.setText(_translate("trolleyWindow", "Continue", None))
        self.instructions.setText(_translate("trolleyWindow", "Please read the instructions below carefully and then press \'Continue\'.\n"
"\n"
"You will take part in two scenarios. In both, you will see a ball moving across the screen towards photos of five children from the Canaan\'s Children\'s Home. There will also be a photo of another child not in the path of the ball. Any children whose photo is hit by the ball would lose the money to buy a meal. Each child will appear only once.", None))
        self.instructionsExp1.setText(_translate("trolleyWindow", "Text 1st experiment", None))
        self.instructionsExp2.setText(_translate("trolleyWindow", "Text 2nd experiment", None))
        self.labelExp1.setText(_translate("trolleyWindow", "Instructions", None))
        self.label_14.setText(_translate("trolleyWindow", "Scenario 1", None))
        self.labelExp2.setText(_translate("trolleyWindow", "Scenario 2", None))
        self.person5.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person1.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person2.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person4.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person3.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person5_3.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person1_3.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person2_3.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person4_3.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person3_3.setText(_translate("trolleyWindow", "TextLabel", None))
        self.infoLabelSidetrackDemo1.setText(_translate("trolleyWindow", "If you did not press the switch button before the ball crosses the line, the upper left group would lose the money for their meals.", None))
        self.label.setText(_translate("trolleyWindow", "Switch", None))
        self.continueSidetrackDemo1Button.setText(_translate("trolleyWindow", "Continue", None))
        self.label_10.setText(_translate("trolleyWindow", "Demonstration 1", None))
        self.continueSidetrackDemo2Button.setText(_translate("trolleyWindow", "Continue", None))
        self.person5_4.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person1_4.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person2_4.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person4_4.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person3_4.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person5_6.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person1_6.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person2_6.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person4_6.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person3_6.setText(_translate("trolleyWindow", "TextLabel", None))
        self.infoLabelSidetrackDemo2.setText(_translate("trolleyWindow", "If you did press the switch button before the ball crosses the line, you will divert the ball towards the other group. They would lose their meals instead.", None))
        self.label_4.setText(_translate("trolleyWindow", "Switch", None))
        self.label_36.setText(_translate("trolleyWindow", "Demonstration 2", None))
        self.switchButtonExp.setText(_translate("trolleyWindow", "Switch", None))
        self.continueSidetrackExpButton.setText(_translate("trolleyWindow", "Continue", None))
        self.confirmSidetrackRatingButton.setText(_translate("trolleyWindow", "Confirm", None))
        self.label_16.setText(_translate("trolleyWindow", "How wrong or right was it to switch the lever?\n"
"\n"
"Choose a rating and click \'Confirm\' ", None))
        self.radioButton.setText(_translate("trolleyWindow", "1", None))
        self.radioButton_3.setText(_translate("trolleyWindow", "3 ", None))
        self.radioButton_6.setText(_translate("trolleyWindow", "6 ", None))
        self.radioButton_5.setText(_translate("trolleyWindow", "5", None))
        self.radioButton_4.setText(_translate("trolleyWindow", "4  ", None))
        self.radioButton_8.setText(_translate("trolleyWindow", "8 ", None))
        self.radioButton_2.setText(_translate("trolleyWindow", "2 ", None))
        self.radioButton_7.setText(_translate("trolleyWindow", "7 ", None))
        self.radioButton_9.setText(_translate("trolleyWindow", "9", None))
        self.label_DefWrong.setText(_translate("trolleyWindow", "Definitely Wrong", None))
        self.label_DefWright.setText(_translate("trolleyWindow", "Definitely Right", None))
        self.label_Neutral.setText(_translate("trolleyWindow", "Neutral", None))
        self.labelSidetrackRatingError.setText(_translate("trolleyWindow", "Please choose a rating and click \'Confirm\'", None))
        self.person5_2.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person1_2.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person2_2.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person4_2.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person3_2.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person5_5.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person1_5.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person2_5.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person4_5.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person3_5.setText(_translate("trolleyWindow", "TextLabel", None))
        self.infoLabelFootbridgeDemo1.setText(_translate("trolleyWindow", "If you did not click on the lower left group before the ball crosses the line, it will carry on and the upper left group would lose their meals.", None))
        self.label_7.setText(_translate("trolleyWindow", "Demonstration 1", None))
        self.continueFootbridgeDemo1Button.setText(_translate("trolleyWindow", "Continue", None))
        self.continueFootbridgeDemo2Button.setText(_translate("trolleyWindow", "Continue", None))
        self.label_11.setText(_translate("trolleyWindow", "Demonstration 2", None))
        self.person5_12.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person1_12.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person2_13.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person4_12.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person3_12.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person5_13.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person1_13.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person2_14.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person4_13.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person3_13.setText(_translate("trolleyWindow", "TextLabel", None))
        self.infoLabelFootbridgeDemo2.setText(_translate("trolleyWindow", "If you did click the lower left group before the ball crosses the line, you would push the lower group into the path of the ball. The pushed group would lose their meals instead.", None))
        self.person5_15.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person1_15.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person2_16.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person4_15.setText(_translate("trolleyWindow", "TextLabel", None))
        self.person3_15.setText(_translate("trolleyWindow", "TextLabel", None))
        self.personFootbridgeSacrifice1.setText(_translate("trolleyWindow", "Clickable Child", None))
        self.continueFootbridgeExpButton.setText(_translate("trolleyWindow", "Continue", None))
        self.confirmFootbridgeRatingButton.setText(_translate("trolleyWindow", "Confirm", None))
        self.radioButton_10.setText(_translate("trolleyWindow", "1", None))
        self.radioButton_11.setText(_translate("trolleyWindow", "3 ", None))
        self.radioButton_12.setText(_translate("trolleyWindow", "6 ", None))
        self.radioButton_13.setText(_translate("trolleyWindow", "5", None))
        self.radioButton_14.setText(_translate("trolleyWindow", "4  ", None))
        self.radioButton_15.setText(_translate("trolleyWindow", "8 ", None))
        self.radioButton_16.setText(_translate("trolleyWindow", "2 ", None))
        self.radioButton_17.setText(_translate("trolleyWindow", "7 ", None))
        self.radioButton_18.setText(_translate("trolleyWindow", "9", None))
        self.label_DefWrong_2.setText(_translate("trolleyWindow", "Definitely Wrong", None))
        self.label_DefWright_2.setText(_translate("trolleyWindow", "Definitely Right", None))
        self.label_Neutral_2.setText(_translate("trolleyWindow", "Neutral", None))
        self.label_17.setText(_translate("trolleyWindow", "How wrong or right was it to push the photo?\n"
"\n"
"Choose a rating below and click \'Confirm\' ", None))
        self.labelFootbridgeRatingError.setText(_translate("trolleyWindow", "Please choose a rating and click \'Confirm\'", None))
        self.endButton.setText(_translate("trolleyWindow", "End experiment", None))
        self.label_18.setText(_translate("trolleyWindow", "Thanks again for taking part. You can now close the window or click \'End experiment\' below.", None))
        self.label_20.setText(_translate("trolleyWindow", "Thank you for taking part in the experiment. It was a partial replication of a 2015 study on moral judgement by Gold, Pulford & Colman.  \n"
" \n"
"If you have further questions about this experiment please contact ucjujrm@ucl.ac.uk. And if you\'d like to know more about this topic, you can read the original paper: \n"
"\n"
"Gold, N., Pulford, B. & Colman, A. (2015). Do as I Say, Don’t Do as I Do: Differences in moral judgments do not translate into differences in decisions in real-life trolley problems. Journal of Economic Psychology, 50-61. ", None))

